Master
php-sepa-xml/php-sepa-xml pull request #175
Opened 2024-12-22 11:06 UTC by FluorFR

Stict address format

2024-12-24 09:38 UTC, FluorFR commented
Good morning,

Here are some proposed modifications for the ISO20022 stand. I didn't write a test, only modifications to the options. This update makes it compatible with the Société Général bank, here is their test site: [https://iso20022.sgmarkets.com/#/](url)

Addresses change format and are strict, and INST mode is necessary for instant SEPA transfers. LclInstrm was misplaced a priori.

2025-01-01 11:29 UTC, BorislavSabev requested changes

2025-01-01 11:29 UTC, BorislavSabev commented on composer.json
> +    "name": "digitick/php-sepa-xml",
This is not correct. Please revert the change.

2025-01-01 11:29 UTC, BorislavSabev commented on src/DomBuilder/CustomerCreditTransferDomBuilder.php
> +        //Generate Street Name address node.
We are not accepting any new fields without test coverage for them so please add the appropriate test cases.

2025-01-01 11:29 UTC, BorislavSabev commented on src/DomBuilder/CustomerCreditTransferDomBuilder.php
> -        // Generate nodes for each address line.
This modification is suspect for a problem. We are supporting specific file versions, not specific banks. This does not look right.

2025-01-01 11:29 UTC, BorislavSabev commented on src/DomBuilder/CustomerCreditTransferDomBuilder.php
> +            $paymentTypeInformation->appendChild($localInstrument);
This modification is wrong. In it's original form it is working with the the payment, not the paymentInfomation.

2025-01-01 14:52 UTC, fluorfr commented on src/DomBuilder/CustomerCreditTransferDomBuilder.php
> +            $paymentTypeInformation->appendChild($localInstrument);
Okay, so I think this is specific to the “Société Générale” bank. Look at the tester who asks us to follow in this way, the same for the addresses. https://iso20022.sgmarkets.com/#/

2025-01-24 08:45 UTC, BorislavSabev commented
@fluorfr I cannot accept these changes as they are specific to one bank. Which is quite odd.
We are contemplating a future version of this library that would allow you to extent it's base classes in order to implement such single-bank changes.

2025-01-24 08:45 UTC, closed without merging